service: farm-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # Stage is based on what is passed in when running serverless
  # commands. Or fallsback to what has been set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so it can be used while testing locally
  # Change table name to farms
  tableName: ${self:custom.stage}-farms
  # Set DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # Load webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # Load secret environment variables based on current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}



provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}
    stripeSecretKey: ${self:custom.environment.stripeSecretKey}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict IAM role permissions to
      # the specific table for the stage
      Resource:
        # Changed to LivestockTable to test building new DynamoDB
        - "Fn::GetAtt": [ LivestockTable, Arn ]
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::studistics-livestock-csv-attachments/*"

functions:
  livestock-analytics:
    handler: livestockAnalytics.averageDailyGain
    events:
      - http:
          path: farms/{id}
          method: post
          cors: true
          authorizer: aws_iam
#      - stream: arn:aws:dynamodb:region:us-east-1:table/process.env.tableName/stream/1970-01-01T00:00:00.000
#      - stream:
#          type: dynamodb
#          arn:
#            Fn::GetAtt: [MyDynamoDbTable, StreamArn]
#      - stream:
#          type: dynamodb
#          arn:
#            Fn::ImportValue: MyExportedDynamoDbStreamArnId
#      - stream:
#          type: kinesis
#          arn:
#            Fn::GetAtt:
#              - MyKinesisStream
#              - Arn
#      - stream:
#          type: kinesis
#          arn:
#            Fn::ImportValue: MyExportedKinesisStreamArnId
#      - stream:
#          type: kinesis
#          arn:
#            Fn::Join:
#              - ':'
#              - - arn
#                - aws
#                - kinesis
#                - Ref: AWS::Region
#                - Ref: AWS::AccountId
#                - stream/MyOtherKinesisStream
  csvHandler:
    # Defines a S3 Bucket that calls the main function in csvHandler.js
    # Defines an HTTP API endpoint that calls the main function in csvHandler.js
    # - path: url path is /farms/{id}
    # - method: POST request
    handler: csvHandler.main
    runtime: nodejs8.10
    events:
      - s3:
          bucket: attachments
          events: s3:ObjectCreated:*
          rules:
            - suffix: .csv
      - http:
          path: farms/{id}
          method: post
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}